config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'top/index'

  resources :threds
  delete 'threds/:id' => 'threds#destroy'

  resources :columns
  root to: "top#index"

  resources :schedules do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :text, presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  def self.import(file)
      xlsx = Roo::Excelx.new(file.tempfile)
      xlsx.each_row_streaming(offset: 1) do |row|
        schedule = self.new(year: row[3].value, month: row[4].value, date: row[0].value, event: row[2].value, day: row[1].value)
        schedule.save
      end
  end

end

app/models/thred.rb
class Thred < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :threds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configre_permitted_parameters, if: :devise_controller?

  private

  def configre_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :set_column, only: [:edit, :update, :show, :destroy]
  def index
    @columns = Column.all
  end

  def new
    @column = Column.new
  end

  def create
    @column = Column.new(column_params)
    if @column.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @column.update(column_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
  end


  def destroy
    if @column.destroy
      redirect_to root_path
    else
      render :root_path
    end
  end

  private

  def column_params
    params.require(:column).permit(:title, :text).merge(user_id: current_user.id)
  end

  def set_column
    @column = Column.find(params[:id])
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedule = Schedule.where(['year LIKE ?', "%#{20}%"]).last
    @month = Schedule.where.not(month: "-").last
    @schedules = Schedule.order(created_at: :desc).limit(31)
  end

  def import
    Schedule.import(params[:file])
    redirect_to root_path
  end

end

app/controllers/threds_controller.rb
class ThredsController < ApplicationController
  before_action :set_thred, only: [:edit, :update, :show, :destroy]
  def index
    @threds = Thred.all
    @columns = Column.last(3)
    @schedule = Schedule.where(['year LIKE ?', "%#{20}%"]).last
    @month = Schedule.where.not(month: "-").last
    @schedules = Schedule.order(created_at: :desc).limit(31)
  end

  def new
    @thred = Thred.new
  end

  def create
    @thred = Thred.new(thred_params)
    if @thred.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @thred.update(thred_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
  end


  def destroy
    if @thred.destroy
      redirect_to root_path
    else
      render :root_path
    end
  end

  private

  def thred_params
    params.require(:thred).permit(:title,:content,:user_id).merge(user_id: current_user.id)
  end

  def set_thred
    @thred = Thred.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @threds = Thred.order(created_at: :desc).limit(2)
    @columns = Column.order(created_at: :desc).limit(3)
    @schedule = Schedule.where(['year LIKE ?', "%#{20}%"]).last
    @month = Schedule.where.not(month: "-").last
    @schedules = Schedule.order(created_at: :desc).limit(31)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/threds_helper.rb
module ThredsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/columns/edit.html.erb
<%= render "shared/header" %>
<!--show.cssを使用-->
<section>
  <div class="inner">
    <div class="show-main">
      <h1 class="show_title">コラム編集ページ</h1>
      <%= form_with model:@column, url: column_path, local: true do |f| %>
        <div class="form-wrap">
          <%= f.text_field :title, placeholder: "タイトル", class: "title_place"%>
        </div>
        <div class="form-wrap">
          <%= f.text_area :text, placeholder: "テキストを入力してください", class:"content_place"%>
        </div>
        <%= f.submit 'POST', class: "btn"%>
      <% end %>
      <%= link_to 'トップへ戻る', root_path %>
    </div>
  </div>
</section>

<%= render "shared/footer" %>

app/views/columns/index.html.erb
<%= render "shared/header" %>
  <% breadcrumb :columns %> 
  <%= breadcrumbs separator: " > " ,class: "bread"%>
<!--thred.cssを使用-->
<div class="thred-main">
  <section id="mv">
    <div class="inner">
      <div class="mv">
        <%= image_tag "mv_4.jpg", class: "mv-img"%>
      </div>
    </div>
  </section>

  <section id="columns">
    <div class="inner">
      <h1>Column<span class="title-rb">コラム</span></h1>
      <div class="column">
          <% if user_signed_in? %>
            <%= link_to '新規投稿', new_column_path %>
          <% end %>
        <% @columns.each do |column| %>
           <ul>
              <li>
                <%= link_to(column_path(column.id)) do %>
                  <span class="column-title"><%= column.title%></span>
                  <span class="date"><%= column.created_at.strftime('%m/%d')%></span>
                  <span class="column-text"><%= simple_format(column.text.truncate(15)) %></span>
                <% end %>
              </li>
            </ul>
        <% end %>
      </div>
    </div>
  </section>
</div>


<%= render "shared/footer" %>

app/views/columns/new.html.erb
<%= render "shared/header" %>
  <% breadcrumb :new_column %> 
  <%= breadcrumbs separator: " > ", class: "bread"%>
<!--show.cssを使用-->
<section>
  <div class="inner">
    <div class="show-main">
    <%= render 'shared/error', model: @column, class:'error' %>
      <h1 class="show_title">コラム投稿ページ</h1>
      <%= form_with model:@column, url: columns_path, local: true do |f| %>
        <div class="form-wrap">
          <%= f.text_field :title, placeholder: "タイトル", class: "title_place"%>
        </div>
        <div class="form-wrap">
          <%= f.text_area :text, placeholder: "テキストを入力してください", class:"content_place"%>
        </div>
        <%= f.submit 'POST', class: "btn"%>
      <% end %>
      <%= link_to 'トップへ戻る', root_path %>
    </div>
  </div>
</section>

<%= render "shared/footer" %>

app/views/columns/show.html.erb
<%= render "shared/header" %>

<section>
  <div class="inner show">
    <div class="show-main">
      <h1 class="show_title"><%= @column.title %></h1>
      <div class="show_content">
        <%= simple_format(@column.text) %>
        <p class="date"><%= @column.created_at.strftime('%m/%d')%></p>
      </div>
      
      <% if user_signed_in? %>
        <div>
          <%= link_to '編集', edit_column_path(@column) %>
          <%= link_to '削除', column_path(@column), method: :delete %>
        </div>
      <% end %>
    </div>
  </div>
<section>



<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HappuSoccer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  <body>
    <%= yield %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </body>
</html>

app/views/schedules/index.html.erb
<%= render "shared/header" %>
  <% breadcrumb :schedules %> 
  <%= breadcrumbs separator: " > ", class: "bread"%>

<div class="main">

  <section id="mv">
    <div class="inner">
      <div class="mv">
        <%= image_tag "mv_5.jpg", class: "mv-img"%>
      </div>
    </div>
  </section>

  
  
  <section id="schedule">
    <div class="inner">
      <h1>Schedule<br /><span class="title-rb">月間スケジュール</span></h1>
      <%#= render 'shared/error', model: , class:'error' %>
      <% if user_signed_in? %>
        <%= form_with url: import_schedules_path, local: true do |f| %>
          <%= f.file_field :file %>
          <%= f.submit %>
        <% end %>
      <% end %>
        <table>
          <% if @schedule.blank? %>
            <p>スケジュールが登録されていません</p>
          <% else %>
            <h2>
              <%= @schedule.year %><span>年度</span>
              <%= @month.month %><span>月のスケジュール</span>
            </h2>
          <%end%>
          </div>
            <thead>
              <tr>
                <th class="days">日</th>
                <th class="days">曜日</th>
                <th class="event">行事</th>
              </tr>
            </thead>
            <tbody>
            <% @schedules.reverse_each do |schedule| %>
              <tr>
                <td class="day"><%= schedule.date %></td>
                <td id="day" class="day"><%= schedule.day %></td>
                <td class="event"><%= schedule.event %></td>
              </tr>
            <% end %>
          </tbody>
        </table>  
    </div>
  </section>
</div>

<%= render "shared/footer" %>

app/views/shared/_error.html.erb
<% if model.errors.any? %>
 <div class="error-alert">
   <ul>
     <% model.errors.full_messages.each do |message| %>
       <li class='error-message'><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-wrap">
    <div class="footer-link">
      <%= link_to 'トップページ', root_path %>
      <%= link_to '掲示板', threds_path %>
      <%= link_to 'スケジュール', schedules_path%>
      <%= link_to 'コラム', columns_path%>
    </div>
    <p class="copyright">© 八風中学校サッカー部</div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header-wrapper">
    <h1 class="logo">
      <%= link_to root_path do%>
        <%= image_tag "happulogo.png", class: "logo-img"%>
      <% end %>
    </h1>
      
    <div class="top-menu">
      <div class="burger-btn"><!-- ③ハンバーガーボタン -->
         <span class="bar bar_top"></span>
         <span class="bar bar_mid"></span>
         <span class="bar bar_bottom"></span>
      </div>
      <div class="nav-wrapper"><!-- ②ナビゲーションメニュー -->
        <nav class="header-nav">
          <ul class="nav-list">
            <li class="menu-list"><%= link_to '掲示版', threds_path %></li>
            <li class="menu-list"><%= link_to '月間スケジュール', schedules_path%></li>
            <li class="menu-list"><%= link_to 'コラム', columns_path %></li>
            <% if user_signed_in? %>
              <li class="menu-list"><%= link_to 'ログアウト', destroy_user_session_path , method: :delete %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/threds/edit.html.erb
<!--未使用-->
<h1>thred edit</h1>
<%= @thred.content %>
<%= form_with model:@thred, url: thred_path, local: true do |f| %>
  <%= f.text_area :content, placeholder:"コンテンツ（必須 40文字まで)", maxlength:"40" %>
  <%= f.submit "変更する" ,class:"sell-btn" %>
<% end %>

 <%= link_to 'トップへ戻る', root_path %>

app/views/threds/index.html.erb
<%= render "shared/header" %>
  <% breadcrumb :thred  %>
  <%= breadcrumbs separator: " > ", class: "bread"%>

<div class="thred-main">
  <section id="mv">
    <div class="inner">
      <div class="mv">
        <%= image_tag "mv_6.jpg", class: "mv-img"%>
      </div>
    </div>
  </section>

  <section id="news">
    <div class="inner">
      <h1>News<span class="title-rb">掲示板</span></h1>
      <div class="news-wrap">
        <div class="threds-index">
          <% if user_signed_in? %>
            <%= link_to '新規投稿', new_thred_path , class:"new-btn"%>
          <% end %>
            <% @threds.each do |thred|%>
            <ul>
              <li>
                <%= link_to(thred_path(thred.id)) do %>
                  <span class="thred-title"><%= thred.title%></span>
                  <span class="date"><%= thred.created_at.strftime('%m/%d')%></span>
                  <span class="thred-content"><%= simple_format(thred.content.truncate(15)) %></span>
                <% end %>
                <% if user_signed_in? %>
                  <%= link_to '編集', edit_thred_path(thred) %>
                  <%= link_to '削除', thred_path(thred) %>
                <%end%>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>


<%= render "shared/footer" %>

app/views/threds/new.html.erb
<%= render "shared/header" %>
  <% breadcrumb :new_thred %> 
  <%= breadcrumbs separator: " > ", class: "bread"%>
<!--show.cssを使用-->
<section>
  <div class="inner">
    <div class="show-main">
    <%= render 'shared/error', model: @thred, class:'error' %>
      <h1 class="show_title">掲示板投稿ページ</h1>
      <%= form_with model:@thred, url: threds_path, local: true do |f| %>
        <div class="form-wrap">
          <%= f.text_field :title, placeholder: "タイトル", class: "title_place"%>
        </div>
        <div class="form-wrap">
          <%= f.text_area :content, placeholder: "テキストを入力してください", class:"content_place"%>
        </div>
        <%= f.submit 'POST', class: "btn"%>
      <% end %>
      <%= link_to 'トップへ戻る', root_path %>
    </div>
  </div>
</section>

<%= render "shared/footer" %>

app/views/threds/show.html.erb
<%= render "shared/header" %>

<section>
  <div class="inner show">
    <div class="show-main">
      <h1 class="show_title"><%= @thred.title %></h1>
      <div class="show_content">
        <%= simple_format(@thred.content) %>
        <p class="date"><%= @thred.created_at.strftime('%m/%d')%></p>
      </div>
      
      <% if user_signed_in? %>
        <div>
          <!--<%= link_to '編集', edit_thred_path(@thred) %>-->
          <%= link_to '削除', thred_path(@thred), method: :delete %>
        </div>
      <% end %>
    </div>
  </div>
<section>


<%= render "shared/footer" %>